"""Workspace-level file layout: what is generated, and how to remove it safely.

This module exists for one reason, and the reason is a scar. The obvious way to
reset a workspace is a shell glob:

    rm -rf 40-runs/*.md 10-returns/*

That also deletes the README documenting each directory, and `git add -A` then
stages the deletion without comment. It happened twice here before anyone
noticed, leaving two directories in the repository with no explanation of what
wrote them or why they must not be edited by hand.

So removal is a function with an explicit keep-list, it lives in `runner/`
rather than in the CLI — the CLI parses arguments and prints, it does not decide
things — and it has a test that fails if a README ever disappears again.
"""

from __future__ import annotations

import pathlib
import shutil

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Directories whose contents are generated by runs. Their README is not.
GENERATED_DIRS = ("10-returns", "40-runs")

# Individual generated files.
GENERATED_FILES = (
    "20-graph/outcomes.jsonl",     # the routing policy's entire memory
    "20-graph/substrate.json",     # last probe result
    "30-queries/needs-human.md",   # the human queue
)

# Never removed, in any directory, for any reason.
KEEP = ("README.md",)


def clean(root: pathlib.Path | None = None) -> list[str]:
    """Remove generated artifacts. Return what was removed, relative to root.

    `root` is resolved at call time so a test — or a second workspace — can
    point this somewhere else. A module-level default would bind at import and
    silently operate on the real workspace instead, which is a mistake this
    project has already made once, in `gate.escalate()`.

    Note what this erases: `outcomes.jsonl` is not a log, it is everything the
    routing policy knows. After a clean, every capability is unproven again and
    will start from its declared floor tier.
    """
    root = root or ROOT
    removed: list[str] = []

    for directory in GENERATED_DIRS:
        target = root / directory
        if not target.exists():
            continue
        for child in sorted(target.iterdir()):
            if child.name in KEEP:
                continue
            if child.is_dir():
                shutil.rmtree(child)
            else:
                child.unlink()
            removed.append(str(child.relative_to(root)))

    for relative in GENERATED_FILES:
        target = root / relative
        if target.exists():
            target.unlink()
            removed.append(relative)

    return removed
